name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Vérification du code
        uses: actions/checkout@v4
      
      - name: Configuration PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, pdo_pgsql
          coverage: xdebug
      
      - name: Installation des dépendances
        run: composer install --prefer-dist --no-progress
      
      - name: Configuration de la base de données en PostgreSQL
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/test_db?serverVersion=16&charset=utf8
      
      - name: Lancement des tests PHPUnit
        run: php bin/phpunit --coverage-text
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/test_db?serverVersion=16&charset=utf8
      
      # - name: 🔍 PHP CS Fixer (style)
      #   run: vendor/bin/php-cs-fixer fix --dry-run --diff
      
      # - name: 📊 PHPStan (analyse statique)
      #   run: vendor/bin/phpstan analyse src --level=5